// @vitest-environment node
import fs from 'node:fs'
import path from 'node:path'
import { describe, expect, it } from 'vitest'

const script = fs.readFileSync(path.resolve('scripts/deploy/install-production-service.sh'), 'utf8')
const restoreScript = fs.readFileSync(path.resolve('scripts/deploy/restore-production.sh'), 'utf8')
const smokeScript = fs.readFileSync(path.resolve('scripts/deploy/smoke-production.mjs'), 'utf8')
const smokeWait = fs.readFileSync(path.resolve('scripts/deploy/wait-for-smoke-health.mjs'), 'utf8')

describe('Production-Installer-Vertrag', () => {
  it('baut und prüft einen validierten staged Kandidaten vor Stop und Symlink-Swap', () => {
    expect(script).toContain('RELEASES_DIR=$BASE_DIR/releases')
    expect(script).toContain('candidate_resolved=$(readlink -f -- "$candidate")')
    expect(script).toContain('[[ $candidate_resolved != "$candidate"')
    const build = script.indexOf('runuser -u pace -- /usr/bin/npm --prefix "$candidate" run build')
    const smoke = script.indexOf('scripts/deploy/smoke-production.mjs')
    const activation = script.indexOf('activation_started=true')
    const stop = script.indexOf('systemctl stop pace.service', activation)
    const inactive = script.indexOf('systemctl is-active --quiet pace.service', stop)
    const backup = script.indexOf('PACE_BACKUP_FILENAME=', inactive)
    const unitInstall = script.indexOf('"$candidate/deploy/pace.service"', backup)
    const swap = script.indexOf('mv -Tf -- "$next_link" "$CURRENT_LINK"')
    expect(build).toBeGreaterThan(0)
    expect(smoke).toBeGreaterThan(build)
    expect(activation).toBeGreaterThan(smoke)
    expect(stop).toBeGreaterThan(activation)
    expect(inactive).toBeGreaterThan(stop)
    expect(backup).toBeGreaterThan(inactive)
    expect(unitInstall).toBeGreaterThan(backup)
    expect(swap).toBeGreaterThan(unitInstall)
    expect(script).toContain('chmod -R u=rwX,g=rX,o= "$candidate"')
    expect(script).toContain('flock -n 9')
  })

  it('gibt jedem Smoke-Serverstart eine monotone belastbare Deadline', () => {
    expect(smokeScript).toContain('const STARTUP_TIMEOUT_MS = 20_000')
    expect(smokeScript).toContain('return waitForHealthyChild({')
    expect(smokeWait).toContain('const deadline = monotonicNow() + startupTimeoutMs')
    expect(smokeWait).toContain('while (monotonicNow() < deadline)')
    expect(smokeWait).toContain('AbortSignal.timeout')
    expect(smokeWait).toContain('assertChildRunning()')
    expect(smokeWait).toContain('Healthcheck-Timeout:\\n${diagnostics()}')
    expect(smokeScript).not.toContain('attempt < 50')
  })

  it('paart DB-Backup und alten Symlink und hat einen Sidecar-sicheren Fehlerrollback', () => {
    expect(script).toContain('release_backup_dir=$BACKUP_DIR/releases/$release_id')
    expect(script).toContain('pace-rollback-$release_stamp.sqlite')
    expect(script).toContain('archive_live_database_checked "$release_backup_dir/failed-activation-$release_stamp"')
    expect(script).toContain('install -o pace -g pace -m 0600 "$rollback_snapshot" "$DATABASE_PATH"')
    expect(script).toContain('mv -Tf -- "$rollback_link" "$CURRENT_LINK"')
    expect(script).toContain('pace.sqlite-wal')
    expect(script).toContain('pace.sqlite-shm')
    expect(script).not.toMatch(/\brm\s+-rf\b/)
    expect(script).toContain("trap on_exit EXIT")
    expect(script).toContain("trap 'exit 130' INT")
    expect(script).toContain("trap 'exit 143' TERM")
    expect(script).toContain('service_was_enabled=false')
    expect(script).toContain('prior_units_dir=')
    expect(script.indexOf('activation_intent=true')).toBeLessThan(script.indexOf('mv -Tf -- "$next_link" "$CURRENT_LINK"'))
    expect(script).toContain('current_target=$(readlink -f -- "$CURRENT_LINK"')
    expect(script).toContain('Rollback nicht vollständig')
  })

  it('liefert ein flock-geschütztes transaktionales Restore mit Vorprüfung und Safety-Rollback', () => {
    const verify = restoreScript.indexOf('"$route_verifier" input "$current_release" "$target_release" "$backup_path"')
    const stop = restoreScript.indexOf('systemctl stop pace.service', verify)
    const safetyBackup = restoreScript.indexOf('PACE_BACKUP_FILENAME="pace-rollback-$restore_stamp.sqlite"', stop)
    const safetyReady = restoreScript.indexOf('safety_snapshot_ready=true', safetyBackup)
    const intent = restoreScript.indexOf('data_move_intent=true', safetyReady)
    const archive = restoreScript.indexOf('move_database_set_checked "$safety_dir/original-files"', intent)
    const install = restoreScript.indexOf('install -o pace -g pace -m 0600 "$backup_path" "$DATABASE_PATH"', archive)
    expect(verify).toBeGreaterThan(0)
    expect(stop).toBeGreaterThan(verify)
    expect(safetyBackup).toBeGreaterThan(stop)
    expect(safetyReady).toBeGreaterThan(safetyBackup)
    expect(intent).toBeGreaterThan(safetyReady)
    expect(archive).toBeGreaterThan(intent)
    expect(install).toBeGreaterThan(archive)
    expect(restoreScript).toContain('flock -n 9')
    expect(restoreScript).toContain('pace.sqlite-wal')
    expect(restoreScript).toContain('pace.sqlite-shm')
    expect(restoreScript).toContain('rollback_restore')
    expect(restoreScript).toContain('move_database_set_checked "$failed_dir"')
    expect(restoreScript).toContain('Fail-closed; nicht starten')
    expect(restoreScript.indexOf('code_activation_intent=true')).toBeLessThan(restoreScript.indexOf('mv -Tf -- "$next_link" "$CURRENT_LINK"'))
    expect(restoreScript).toContain("trap 'exit 130' INT")
    expect(restoreScript).not.toMatch(/\brm\s+-rf\b/)
  })
})
